### ISSUE TITLE
Cannot found in HACS

### ISSUE THREAD

**Issue by zenz** [yury-sannikov/ha-mqtt-water-heater#1]
Hi,
I try to install this plugin in HACS, but while browsing all repositories, this is not exist? then how can I install it?

**Comment by yury-sannikov** [comment]
oh man, sorry, didn't get GitHub notifications.
You need to add this repo as a custom repository in HACS. Check out this https://hacs.xyz/docs/faq/custom_repositories

**Comment by mihsu81** [comment]
Hi @zenz, after adding i as a custom repository in HACS (from the 3 vertical dots in the upper right corner), you have to add it as a repository in HACS using the button "EXPLORE & ADD REPOSITORIES".
And the last step is to add it as a platform for the "water_heater" domain in configuration.yaml.
Something like this:
```
water_heater:
  platform: mqtt_water_heater
  name: "OpenTherm Gateway Hot Water"
  target_temperature: 45
  heater_min_temperature: 35
  heater_max_temperature: 60
  state_topic: "opentherm-thermostat/dhw-temperature/get"
  command_topic: "opentherm-thermostat/dhw-temperature/set"
```

**Comment by yury-sannikov** [comment]
Hi, I think I need to archive this repository. Please use something like this:
```
  - platform: mqtt
    name: Hot Water Boiler
    send_if_off: true
    initial: 37
    min_temp: 35
    max_temp: 60
    icon: mdi:water-pump
    current_temperature_topic: "tele/boiler/SENSOR"
    current_temperature_template: "{{ value_json.get('OPENTHERM', {}).get('TDHW', 0) }}"
    availability_topic: "tele/boiler/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"  
    precision: 1.0
    temperature_command_topic: "cmnd/boiler/ot_twater"
    temperature_state_topic: "tele/boiler/SENSOR"
    temperature_state_template: "{{ value_json.get('OPENTHERM', {}).get('DHWS', 0) }}"
    temperature_unit: "C"
    modes:
      - "off"
      - "heat"
```
